version: 2.1

orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  # different jobs are calles later in the workflows sections

executors:
  custom:
    docker:
      - image: "cimg/base:stable"
jobs:
  build:
    executor: custom
    steps:
      - node/install:
          install-yarn: true
      - checkout
      # install dependencies in both apps
      - run:
          name: Frontend install
          command: |
            npm run frontend:install
      - run:
          name: Backend install
          command: |
            npm run backend:install 

      - run:
          name: backend build
          command: |
            npm run backend:build
      - run:
          name: frontend build
          command: |
            npm run frontend:build
      - persist_to_workspace:
          root: /temp
          paths:
            - build

  deploy:
    executor: custom
    steps:
      - attach_workspace:
          at: /temp/build
      - node/install
      - aws-cli/setup
      - checkout
      - run:
          name: deploy to aws
          command: |
            npm run frontend:deploy
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
